---
- name: Get list of private SSH keys to deploy from DEPLOY_PRIVATE_SSH_KEYS
  set_fact:
    ssh_keys: "{{ (lookup('env', 'DEPLOY_PRIVATE_SSH_KEYS') | default('')).split(',') | map('trim') | list }}"
  when: lookup('env', 'DEPLOY_PRIVATE_SSH_KEYS') | default('') | trim != ''
  tags:
    - deploy

- name: Deploy private SSH keys
  copy:
    content: "{{ lookup('env', item) }}"
    dest: "/home/ansible/.ssh/{{ item }}"
    owner: ansible
    group: ansible
    mode: '0600'
  loop: "{{ ssh_keys | default([]) }}"
  when: ssh_keys is defined
  tags:
    - deploy

- name: Start ssh-agent and add SSH keys
  shell: |
    eval "$(ssh-agent -s)"
    ssh-add /home/ansible/.ssh/{{ item }}
  loop: "{{ ssh_keys | default([]) }}"
  when: ssh_keys is defined
  tags:
    - deploy
