---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Remove default nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: List enabled Nginx config templates (*.conf.j2 only)
  find:
    paths: "../deployment/templates/nginx"
    patterns: "*.conf.j2"
    recurse: false
  register: nginx_config_files
  delegate_to: localhost
  tags:
    - deploy

- name: Copy custom Nginx configs
  template:
    src: "{{ item.path }}"
    dest: "/etc/nginx/sites-enabled/{{ item.path | basename | regex_replace('\\.conf\\.j2$', '') }}"
  loop: "{{ nginx_config_files.files }}"
  when: nginx_config_files.matched > 0
  notify:
    - Restart Nginx
  tags:
    - deploy

- name: Copy Nginx portainer config
  template:
    src: portainer.conf.j2
    dest: /etc/nginx/sites-enabled/portainer
  notify:
    - Restart Nginx
  tags:
    - portainer
    - configure_host

- name: Enable Nginx
  service:
    name: nginx
    enabled: yes
    state: started

- name: Nginx is running
  service:
    name: nginx
    state: started
