all:
  hosts:
    main:
      ansible_host: "{{ lookup('env', 'HOST') }}"
      ansible_user: "{{ lookup('env', 'ANSIBLE_USER') }}"
      ansible_ssh_private_key_file: "ssh/{{ lookup('env', 'ENV') }}_private_key"
