services:
  app:
    image: my-app-${ENV}:${VERSION}
    build:
      context: ../..
      dockerfile: Dockerfile.app
    environment:
      ENV: ${ENV}
    restart: always
    ports:
      - "${APP_EXTERNAL_PORT}:3000"