---
- name: Determine docker images directory based on host
  set_fact:
    docker_images_path: "{{ '../../docker_images_' + lookup('env', 'HOST_SUFFIX') if lookup('env', 'HOST_SUFFIX') and lookup('env', 'HOST_SUFFIX') != 'main' else '../../docker_images' }}"

- name: List all .tar files on local server (where Ansible is running)
  find:
    paths: "{{ docker_images_path }}"
    patterns: "*.tar"
  delegate_to: localhost
  register: tar_files

- name: Display docker images directory being used
  debug:
    msg: "Using docker images directory: {{ docker_images_path }}"

- name: Copy all Docker images to remote server
  copy:
    src: "{{ item.path }}"
    dest: "/tmp/{{ item.path | basename }}"
  loop: "{{ tar_files.files | default([]) }}"
  register: copy_output

- name: Load Docker images on remote server
  command: "docker load -i /tmp/{{ item.path | basename }}"
  loop: "{{ tar_files.files | default([]) }}"

- name: Delete loaded tar files
  file:
    path: "/tmp/{{ item.path | basename }}"
    state: absent
  loop: "{{ tar_files.files | default([]) }}"
