stages:
  - build
  - deploy

image: shawiizz/devops-ci:1.0.0

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  ANSIBLE_REPOSITORY_URL: https://github.com/Shawiizz/devops.git

before_script:
  - |
    TAG=$CI_COMMIT_REF_NAME
    ENVIRONMENT="production"

    if [[ "$TAG" == *"-"* ]]; then
      ENVIRONMENT="${TAG##*-}"
    fi

    while read -r line; do
      [[ "$line" =~ ^[A-Za-z_][A-Za-z0-9_]*= ]] && export "$line"
    done < "deployment/env/.env.${ENVIRONMENT}"

    export ENV=$ENVIRONMENT
    export VERSION=$TAG

build:
  stage: build
  script:
    - |
      cd deployment/docker
      IFS=',' read -ra SERVICES <<< "$DEPLOY_DOCKER_SERVICES"
      for SERVICE in "${SERVICES[@]}"; do
        echo "Building service: $SERVICE"
        BUILD_CMD=$(decomposerize compose-deploy.yml --services="$SERVICE" --docker-build)
        echo "Running: $BUILD_CMD"
        eval "$BUILD_CMD"

        IMAGE_NAME=$(echo "$BUILD_CMD" | sed -nE 's/.*-t\s+"?([^"]+)"?.*/\1/p')
        IMAGE_NAME=$(eval echo "$IMAGE_NAME")
        echo "Image built: $IMAGE_NAME"

        TAR_NAME="${IMAGE_NAME//:/-}.tar"
        docker save -o "$TAR_NAME" "$IMAGE_NAME"

        echo "::group::Upload $TAR_NAME"
        echo "artifact: image-${SERVICE}"
        echo "Path: $(realpath "$TAR_NAME")"
        echo "::endgroup::"
      done

  artifacts:
    paths:
      - deployment/docker/*.tar
    expire_in: 1 day

deploy:
  stage: deploy
  needs: ["build"]
  rules:
    - if: '$CI_COMMIT_TAG'
  script:
    - |
      git clone $ANSIBLE_REPOSITORY_URL ansible

      mkdir -p ./docker_images
      cp deployment/docker/*.tar ./docker_images/

      mkdir -p ansible/ssh
      SSH_SECRET_NAME="$(echo "${ENV}" | tr '[:lower:]' '[:upper:]')_SSH_PRIVATE_KEY"
      SSH_KEY_VALUE=$(printenv "$SSH_SECRET_NAME")
      echo "$SSH_KEY_VALUE" | tr -d '\r' > ansible/ssh/main_private_key
      chmod 600 ansible/ssh/*
      
      eval "$(ssh-agent -s)"
      ssh-add ansible/ssh/main_private_key

      cd ansible
      export ANSIBLE_HOST_KEY_CHECKING=False
      export ANSIBLE_BECOME_PASSWORD=$ANSIBLE_BECOME_PASSWORD

      ansible-galaxy role install geerlingguy.docker
      ansible-playbook deploy.yml -i "$HOST," --user="$ANSIBLE_USER" --private-key=ansible/ssh/main_private_key --skip-tags "configure_host"
