include:
  - remote: 'https://raw.githubusercontent.com/Shawiizz/devops/refs/tags/1.0.23/.gitlab/common/steps.yml'
  - remote: 'https://raw.githubusercontent.com/Shawiizz/devops/refs/tags/1.0.23/.gitlab/common/variables.yml'

stages:
  - build-and-deploy

build-and-deploy:
  stage: build-and-deploy
  rules:
    - if: '$CI_COMMIT_TAG'
  extends:
    - .common-variables
    - .prepare-env
    - .build-docker-images
    - .deploy-with-ansible
