include:
  - remote: 'https://raw.githubusercontent.com/Shawiizz/devops/refs/tags/1.0.23/.gitlab/common/steps.yml'
  - remote: 'https://raw.githubusercontent.com/Shawiizz/devops/refs/tags/1.0.23/.gitlab/common/variables.yml'

stages:
  - deploy
  - deploy-build

deploy:build:
  stage: deploy-build
  rules:
    - if: '$CI_COMMIT_TAG'
  extends:
    - .common-variables
    - .prepare-env
    - .build-docker-images
  artifacts:
    paths:
      - deployment/docker/*.tar
    expire_in: 1 day

deploy:
  stage: deploy
  needs: ["deploy:build"]
  extends:
      - .common-variables
      - .prepare-env
      - .deploy-with-ansible
  rules:
    - if: '$CI_COMMIT_TAG'
