---
- name: Deploy Docker Images to Remote Server
  hosts: all:!localhost
  vars:    
    compose_path: "../../deployment/docker/compose-deploy.yml"
    tmp_dir: "/tmp"
    global_no_log: "{{ not (lookup('env', 'DISABLE_NO_LOG') | default('false', true) | bool) }}"
    deploy_services: "{{ lookup('env', 'DEPLOY_DOCKER_SERVICES') | default('', true) }}"
    services_option: "{{ '--services=' + deploy_services if deploy_services else '' }}"
    decomposerize_types:
      - name: "setup"
        base_options: "--create-networks --create-volumes --stop-and-remove"
        ignore_errors: yes  # Networks/volumes might already exist
      - name: "run"
        base_options: "--docker-run --docker-run-detach"
        ignore_errors: no
      - name: "cleanup"
        base_options: "--delete-images"
        ignore_errors: yes  # New images are used by containers
  roles:
    - role: geerlingguy.docker
    - role: nginx
      tags:
        - nginx
    - role: private_ssh_keys
    - role: services   
    - role: image-transfer
    - role: execute-scripts
  tasks:
    - name: Process Docker commands for each type
      include_tasks: process_docker_commands.yml
      loop: "{{ decomposerize_types }}"
      loop_control:
        loop_var: cmd_type
      no_log: "{{ global_no_log }}"
