---
- name: Deploy Docker Images to Remote Server
  hosts: all:!localhost
  vars:
    compose_path: "../../deployment/docker/compose-deploy.yml"
    tmp_dir: "/tmp"
    decomposerize_types:
      - name: "setup"
        options: "--create-networks --create-volumes --stop-and-remove"
        ignore_errors: yes  # Networks/volumes might already exist
      - name: "run"
        options: "--docker-run --docker-run-detach"
        ignore_errors: no
      - name: "cleanup"
        options: "--delete-images"
        ignore_errors: yes  # New images are used by containers
  roles:
    - role: geerlingguy.docker
    - role: nginx
      tags:
        - nginx
    - role: private_ssh_keys
    - role: services
    - role: image-transfer
      tags:
        - image-transfer    
  tasks:
    - name: Process Docker commands for each type
      include_tasks: process_docker_commands.yml
      loop: "{{ decomposerize_types }}"
      loop_control:
        loop_var: cmd_type
      no_log: true
