stages:
  # Build stage for continuous integration
  - build

  # Deploy your application on tag push
  - deploy

include:
  # Continuous Integration (CI) template for building Docker images (not used for deployment)
  - remote: 'https://raw.githubusercontent.com/Shawiizz/devops-framework/refs/tags/1.0.28/.gitlab/workflows/build.yml'

  # Deploy your application on tag push
  - remote: 'https://raw.githubusercontent.com/Shawiizz/devops-framework/refs/tags/1.0.28/.gitlab/workflows/deploy.yml'
